### ISSUE TITLE
An error occurred: e.trim is not a function

### ISSUE THREAD

**Issue by ezschemi** [notable/dumper#20] opened 2019-10-11 09:12 UTC
- **OS Version**: win32 10.0.18362
- **Notable Version**: v1.7.3

This happened when importing a 370MiB Evernote archive.

```
TypeError: e.trim is not a function
    at file:///C:/Users/ezschemi/AppData/Local/Temp/1PkTDkRCSrHqYbS4UEWcXWoXKUw/resources/app.asar/chunk.fba3d68ffab26c3d35e8.js:1:3424
    at Array.map (<anonymous>)
    at EnexNote.sanitizeMetadata (file:///C:/Users/ezschemi/AppData/Local/Temp/1PkTDkRCSrHqYbS4UEWcXWoXKUw/resources/app.asar/chunk.fba3d68ffab26c3d35e8.js:1:3415)
    at EnexNote.get (file:///C:/Users/ezschemi/AppData/Local/Temp/1PkTDkRCSrHqYbS4UEWcXWoXKUw/resources/app.asar/chunk.fba3d68ffab26c3d35e8.js:1:2798)
    at async EnexProvider.dump (file:///C:/Users/ezschemi/AppData/Local/Temp/1PkTDkRCSrHqYbS4UEWcXWoXKUw/resources/app.asar/chunk.fba3d68ffab26c3d35e8.js:1:2706)
    at async Object.dump (file:///C:/Users/ezschemi/AppData/Local/Temp/1PkTDkRCSrHqYbS4UEWcXWoXKUw/resources/app.asar/chunk.fba3d68ffab26c3d35e8.js:1:57993)
    at async import_Import.import (file:///C:/Users/ezschemi/AppData/Local/Temp/1PkTDkRCSrHqYbS4UEWcXWoXKUw/resources/app.asar/renderer.js:1:21799)
```

**Comment by fabiospampinato** [comment] 2019-10-11 11:57
Duplicate of https://github.com/notable/dumper/issues/10.

It'd be helpful if you could post (or email to me at fabio@notable.md) a file that reproduces the issue.

**Closed as completed by fabiospampinato** 2019-10-11 11:57 UTC

**Comment by ezschemi** [comment] 2019-10-11 12:17
Ok. I have sent you an email with an exported archive from Evernote that shows the issue.

**Comment by fabiospampinato** [comment] 2019-10-11 12:20
@ezschemi Thank you I've just received your emails, the enex files you provided will be extremely useful!
