### ISSUE TITLE
Support Quiver notes

### ISSUE THREAD

**Issue by PatrickF1** [notable/dumper#8] opened 2019-09-10 06:32 UTC
Support importing Quiver (https://happenapps.com/) notes, extension: `.qvnote` and/or `.qvlibrary`. Creating this ticket as a followup to our conversation here https://github.com/notable/notable/issues/810, not trying to be demanding about doing it immediately :)

**Comment by fabiospampinato** [comment] 2019-09-28 22:45
Duplicate of #17

**Closed as completed by fabiospampinato** 2019-09-28 22:45 UTC
Labels: enhancement, help wanted
